# Generated by Django 3.1.5 on 2021-01-29 22:18

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cookbook_dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=255)),
                ('type_of_cuisine', models.CharField(choices=[('Caribbean', 'Caribbean'), ('Vietnamese', 'Vietnamese'), ('Korean', 'Korean'), ('German', 'German'), ('Indian', 'Indian')], max_length=255)),
                ('photo', models.ImageField(upload_to='media/dishes/%Y/%m')),
                ('description', ckeditor.fields.RichTextField()),
                ('cook_time', models.IntegerField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('favorited', models.ManyToManyField(blank=True, default=None, related_name='favorited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('favorite', 'favorite'), ('unfavorite', 'unfavorite')], default='unfavorite', max_length=255)),
                ('favorite_dishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.cookbook_dishes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dish_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cook_dishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cuisine.cookbook_dishes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
