# Generated by Django 3.1.5 on 2021-02-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbook_dishes',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
