# Generated by Django 3.1.5 on 2021-01-29 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish_comment',
            name='created',
        ),
        migrations.AddField(
            model_name='cookbook_dishes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
