# Generated by Django 3.1.5 on 2021-01-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0002_auto_20210130_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbook_dishes',
            name='photo',
            field=models.ImageField(upload_to='media/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='cookbook_dishes',
            name='type_of_cuisine',
            field=models.CharField(choices=[('German', 'German'), ('Indian', 'Indian')], max_length=255),
        ),
    ]
