# Generated by Django 3.1.5 on 2021-02-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0002_auto_20210202_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbook_dishes',
            name='photo',
            field=models.ImageField(upload_to='media/%Y/%m'),
        ),
    ]
