# Generated by Django 3.1.5 on 2021-01-31 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuisine', '0003_auto_20210130_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbook_dishes',
            name='favorited',
        ),
        migrations.AddField(
            model_name='cookbook_dishes',
            name='favourite',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
