# Generated by Django 3.1.5 on 2021-01-31 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0004_auto_20210131_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='favorite',
        ),
    ]
