# Generated by Django 3.1.5 on 2021-01-31 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuisine', '0005_delete_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbook_dishes',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
