# Generated by Django 3.1.5 on 2021-01-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0006_auto_20210131_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook_dishes',
            name='slug',
            field=models.SlugField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
