# Generated by Django 3.1.5 on 2021-01-31 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0007_cookbook_dishes_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbook_dishes',
            name='slug',
        ),
    ]
