# Generated by Django 3.1.5 on 2021-02-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0008_remove_cookbook_dishes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbook_dishes',
            name='type_of_cuisine',
            field=models.CharField(choices=[('GermanAndhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Manipur', 'Manipur')], max_length=255),
        ),
    ]
