# Generated by Django 3.1.5 on 2021-02-01 04:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuisine', '0009_auto_20210201_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook_dishes',
            name='dish_like',
            field=models.ManyToManyField(blank=True, related_name='dish_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
